name: sonar-check

on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-check:
    name: Sonar Cloud Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
